FROM python:3.9

RUN apt-get install wget
RUN pip install --upgrade pip
RUN pip install pandas
RUN pip install sqlalchemy
RUN pip install psycopg2

WORKDIR /app
COPY ingestion.py ingestion.py

ENTRYPOINT [ "python3", "ingestion.py" ]